import type { Database } from "./types";

export const seedDatabase: Database = {
  products: [
    {
      id: "PRD-0001",
      name: "Camiseta Básica Algodão",
      sku: "CAM-BAS-M",
      category: "Vestuário",
      price: 59.9,
      stock: 124,
      status: "ativo",
    },
    {
      id: "PRD-0002",
      name: "Tênis Runner Pro",
      sku: "TEN-RUN-42",
      category: "Calçados",
      price: 289.9,
      stock: 18,
      status: "ativo",
    },
    {
      id: "PRD-0003",
      name: "Mochila Urban 20L",
      sku: "MCH-URB-20",
      category: "Acessórios",
      price: 149.9,
      stock: 0,
      status: "esgotado",
    },
    {
      id: "PRD-0004",
      name: "Relógio Digital Sport",
      sku: "REL-DIG-S",
      category: "Acessórios",
      price: 199.9,
      stock: 42,
      status: "ativo",
    },
    {
      id: "PRD-0005",
      name: "Calça Jeans Slim",
      sku: "CAL-JEA-40",
      category: "Vestuário",
      price: 129.9,
      stock: 8,
      status: "ativo",
    },
    {
      id: "PRD-0006",
      name: "Fone Bluetooth ANC",
      sku: "FON-BT-A",
      category: "Eletrônicos",
      price: 349.9,
      stock: 31,
      status: "ativo",
    },
  ],
  orders: [
    {
      id: "PED-5024",
      customer: "Maria Silva",
      items: 3,
      total: 449.7,
      channel: "E-commerce",
      status: "pago",
      date: "19/05/2026 10:32",
    },
    {
      id: "PED-5023",
      customer: "João Santos",
      items: 1,
      total: 289.9,
      channel: "Loja física",
      status: "enviado",
      date: "19/05/2026 09:15",
    },
    {
      id: "PED-5022",
      customer: "Ana Costa",
      items: 2,
      total: 209.8,
      channel: "WhatsApp",
      status: "pendente",
      date: "18/05/2026 16:48",
    },
    {
      id: "PED-5021",
      customer: "Pedro Lima",
      items: 4,
      total: 679.6,
      channel: "Marketplace",
      status: "cancelado",
      date: "18/05/2026 11:22",
    },
    {
      id: "PED-5020",
      customer: "Fernanda Rocha",
      items: 2,
      total: 499.8,
      channel: "E-commerce",
      status: "enviado",
      date: "17/05/2026 15:10",
    },
  ],
  teamMembers: [
    {
      id: "USR-0001",
      name: "Thais Admin",
      email: "thais@gestify.com.br",
      role: "Administrador",
      status: "ativo",
      lastAccess: "19/05/2026 11:20",
    },
    {
      id: "USR-0002",
      name: "Carlos Estoque",
      email: "carlos@gestify.com.br",
      role: "Estoquista",
      status: "ativo",
      lastAccess: "19/05/2026 09:14",
    },
    {
      id: "USR-0003",
      name: "Ana Vendas",
      email: "ana@gestify.com.br",
      role: "Vendedor",
      status: "ativo",
      lastAccess: "19/05/2026 08:42",
    },
    {
      id: "USR-0004",
      name: "Ricardo Gerente",
      email: "ricardo@gestify.com.br",
      role: "Gerente",
      status: "ativo",
      lastAccess: "18/05/2026 18:00",
    },
    {
      id: "USR-0005",
      name: "Julia Suporte",
      email: "julia@gestify.com.br",
      role: "Vendedor",
      status: "inativo",
      lastAccess: "10/05/2026 14:30",
    },
  ],
  stockMovements: [
    {
      id: "MOV-1042",
      productId: "PRD-0001",
      product: "Camiseta Básica Algodão",
      type: "entrada",
      quantity: 50,
      date: "19/05/2026 09:14",
      user: "Carlos Estoque",
    },
    {
      id: "MOV-1041",
      productId: "PRD-0002",
      product: "Tênis Runner Pro",
      type: "saída",
      quantity: -3,
      date: "19/05/2026 08:42",
      user: "Ana Vendas",
    },
    {
      id: "MOV-1040",
      productId: "PRD-0003",
      product: "Mochila Urban 20L",
      type: "saída",
      quantity: -2,
      date: "18/05/2026 17:20",
      user: "Ana Vendas",
    },
  ],
  notifications: [
    {
      id: "NTF-0001",
      title: "Estoque baixo",
      message: "Calça Jeans Slim está com apenas 8 unidades.",
      type: "estoque",
      read: false,
      createdAt: "19/05/2026 11:05",
      href: "/estoque",
    },
    {
      id: "NTF-0002",
      title: "Pedido pendente",
      message: "PED-5022 aguardando confirmação de pagamento.",
      type: "venda",
      read: false,
      createdAt: "19/05/2026 10:45",
      href: "/vendas",
    },
    {
      id: "NTF-0003",
      title: "Produto esgotado",
      message: "Mochila Urban 20L sem estoque disponível.",
      type: "estoque",
      read: false,
      createdAt: "19/05/2026 09:30",
      href: "/produtos",
    },
  ],
  settings: {
    storeName: "Gestify Store",
    cnpj: "00.000.000/0001-00",
    address: "Av. Paulista, 1000 — São Paulo, SP",
    phone: "(11) 99999-0000",
    email: "contato@gestify.com.br",
    openTime: "09:00",
    closeTime: "21:00",
    operatingDays: "Segunda a sábado",
  },
  categories: [
    { name: "Vestuário", count: 48, revenue: 12450 },
    { name: "Calçados", count: 22, revenue: 18900 },
    { name: "Acessórios", count: 35, revenue: 8320 },
    { name: "Eletrônicos", count: 18, revenue: 15600 },
  ],
};
